

all: packageZh packageJa packageKo
	
	
packageEn2Zh:
	echo "en:zh" > lang.txt
	ant release-zh
	
packageEn2Ja:
	echo "en:ja" > lang.txt
	ant release-ja
	
packageEn2Ko:
	echo "en:ko" > lang.txt
	ant release-ko
	
packageZh2En:
	echo "en:zh" > lang.txt
	ant release-zh
	
packageJa2En:
	echo "en:ja" > lang.txt
	ant release-ja
	
packageKo2En:
	echo "en:ko" > lang.txt
	ant release-ko	
	
en2zh-gt:
	echo "en:zh" > lang.txt
	ant release-en2zh-gt
	
en2ja-gt:
	echo "en:ja" > lang.txt
	ant release-en2ja-gt
	
en2ko-gt:
	echo "en:ko" > lang.txt
	ant release-en2ko-gt
	
zh2en-gt:
	echo "zh:en" > lang.txt
	ant release-zh2en-gt
	
ja2en-gt:
	echo "ja:en" > lang.txt
	ant release-ja2en-gt
	
ko2en-gt:
	echo "ko:en" > lang.txt
	ant release-ko2en-gt	