

all: packageZh packageJa packageKo
	
	
packageZh:
	echo "zh" > lang.txt
	ant release-zh
	
packageJa:
	echo "ja" > lang.txt
	ant release-ja
	
packageKo:
	echo "ko" > lang.txt
	ant release-ko
	
zhgt:
	echo "zh" > lang.txt
	ant release-zh-gt
	
jagt:
	echo "ja" > lang.txt
	ant release-ja-gt
	
kogt:
	echo "ko" > lang.txt
	ant release-ko-gt