//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.07 at 02:27:09 PM EST 
//


package org.inex.ltw.resultsetGenerator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ltwTopicType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ltwTopicType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}outgoingLinks"/>
 *         &lt;element ref="{}incomingLinks"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ltwTopicType", propOrder = {
    "outgoingLinks",
    "incomingLinks"
})
public class LtwTopicType {

    @XmlElement(required = true)
    protected OutlinkingType outgoingLinks;
    @XmlElement(required = true)
    protected InlinkingType incomingLinks;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the outgoingLinks property.
     * 
     * @return
     *     possible object is
     *     {@link OutlinkingType }
     *     
     */
    public OutlinkingType getOutgoingLinks() {
        return outgoingLinks;
    }

    /**
     * Sets the value of the outgoingLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutlinkingType }
     *     
     */
    public void setOutgoingLinks(OutlinkingType value) {
        this.outgoingLinks = value;
    }

    /**
     * Gets the value of the incomingLinks property.
     * 
     * @return
     *     possible object is
     *     {@link InlinkingType }
     *     
     */
    public InlinkingType getIncomingLinks() {
        return incomingLinks;
    }

    /**
     * Sets the value of the incomingLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link InlinkingType }
     *     
     */
    public void setIncomingLinks(InlinkingType value) {
        this.incomingLinks = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
