//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.07 at 02:27:09 PM EST 
//


package crosslink.resultsetGenerator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="alength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="aname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="aoffset" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="boffset" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "outLink")
public class OutLink {

    @XmlValue
    protected String value;
    @XmlAttribute
    protected String alength;
    @XmlAttribute
    protected String aname;
    @XmlAttribute
    protected String aoffset;
    @XmlAttribute
    protected String boffset;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the alength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlength() {
        return alength;
    }

    /**
     * Sets the value of the alength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlength(String value) {
        this.alength = value;
    }

    /**
     * Gets the value of the aname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAname() {
        return aname;
    }

    /**
     * Sets the value of the aname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAname(String value) {
        this.aname = value;
    }

    /**
     * Gets the value of the aoffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAoffset() {
        return aoffset;
    }

    /**
     * Sets the value of the aoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAoffset(String value) {
        this.aoffset = value;
    }

    /**
     * Gets the value of the boffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoffset() {
        return boffset;
    }

    /**
     * Sets the value of the boffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoffset(String value) {
        this.boffset = value;
    }

}
